fixtures:
  repositories:
      stdlib:
        repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
        branch: "v9.4.0"
      augeas_core:
        repo: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
        branch: "v1.4.1"
  symlinks:
    wildfly: "#{source_dir}"
